# Site settings
title: Maxwell Bernstein
email: max@bernsteinbear.com
description: "Programmer and photographer."
username: tekknolagi
baseurl: ""
url: "http://maxbernste.in"

# Build settings
markdown: kramdown
permalink: pretty

links:
  -
    name: Website
    url: http://bernsteinbear.com
    text: bernsteinbear.com
  -
    name: Photos
    url: http://photos.bernsteinbear.com
    text: photos.bernsteinbear.com
